name: Run Script

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # Roda todo dia às 3h UTC

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar script
        run: python main.py