name: Scrape e salva CSV

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # Roda todo dia às 3h UTC

jobs:
  scrape-job:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar script
        run: python main.py

      - name: Configurar Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Commitar e fazer push do CSV
        run: |
          if git diff --quiet; then
            echo "Nenhuma alteração detectada no CSV. Nada para commit."
          else
            git add *.csv
            git commit -m "🔄 Atualiza CSV automaticamente [skip ci]"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}