name: Scrape e salva CSV

on:
  workflow_dispatch:
  schedule:
    # Executa no dia 1 e 16 de cada mês às 3h UTC (~a cada 15 dias)
    - cron: '0 3 1,16 * *'

jobs:
  scrape-job:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar scraper
        run: python main.py

      - name: Atualizar README com estatísticas
        run: python meta.py

      - name: Configurar Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Commitar e fazer push do CSV e README
        run: |
          git add *.csv README.md
          if git status --porcelain | grep .; then
            git commit -m "🔄 Atualiza CSV e README automaticamente [skip ci]"
            git push
          else
            echo "Nenhuma alteração detectada. Nada para commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}